### ISSUE TITLE
Restore previous functionality to "/tourettes"

### ISSUE THREAD

**Issue by Looxoor** [Qw4z1/qw4z1bot#15]
Ensuring 3-10 profanities spewed when using the command without following text.

Also, preferably, the functionality that was under development that made e.g. /tourettes 35 spew 35 random profanities.

**Comment by w1nston** [comment]
Will fix this, but the /tourettes 35 thing is an issue on its own (#5)

**Comment by w1nston** [comment]
Fixed in PR #17

**Comment by Looxoor** [comment]
Strip inputText of commands so that arguments can be properly evaluated.
Remove last method in sayTourettes because one profanity should never be output.
